### ISSUE TITLE
[Question] - Campo Cidade e Duvida Geral

### ISSUE THREAD

**Issue by LuisKrotz** [produtoreativo/empresas-que-usam-pwa-no-brasil#14]
No campo cidade, deve ser adicionada a cidade onde o PWA foi construído, ou a cidade cede da empresa ou organização do site?

Ex, o PWA foi construído em Porto Alegre, porém a cede da organização/site fica em Caxias do Sul.

Ex 2, o PWA foi construído no Brasil, porém para uma empresa/grupo estrangeiro, é considerado na lista de PWAs ou não?

Já existe uma regra para esses casos?

**Comment by cmilfont** [comment]
Fala @LuisKrotz, o repo foi criado com o propósito de mostrar o que nosso mercado está fazendo e engajar as pessoas a descobrirem empresas interessantes pra trabalhar com isso.

Sinceramente, acho que vale colocar até explicação no local cidade com os exemplos que você deu.

Que todo mundo fique a vontade para escrever textão no campo cidade pra atrair interesse.
